name: Update SharpCaster Formula

on:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run updater
        run: |
          chmod +x .github/scripts/update_sharpcaster_formula.sh
          .github/scripts/update_sharpcaster_formula.sh

